
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Aug 20 15:22:25 CEST 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 19;
  public static final int LBRACKET = 5;
  public static final int CONST = 15;
  public static final int CONTINUE = 41;
  public static final int LPAREN = 8;
  public static final int SEMI = 7;
  public static final int FOR = 39;
  public static final int MINUS = 25;
  public static final int RPAREN = 9;
  public static final int AND = 49;
  public static final int OR = 50;
  public static final int COMMA = 10;
  public static final int CLASS = 37;
  public static final int INC = 29;
  public static final int DIV = 27;
  public static final int DIVEQUAL = 34;
  public static final int IF_EQUAL = 43;
  public static final int PLUS = 24;
  public static final int IF = 22;
  public static final int DOT = 42;
  public static final int ABSTRACT = 38;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int RBRACKET = 6;
  public static final int EQUAL = 13;
  public static final int NEW = 16;
  public static final int error = 1;
  public static final int MUL = 26;
  public static final int IF_LESS = 47;
  public static final int IF_GREATER = 45;
  public static final int PLUSEQUAL = 31;
  public static final int NUMBER = 18;
  public static final int MOD = 28;
  public static final int BREAK = 36;
  public static final int IDENT = 20;
  public static final int VOID = 14;
  public static final int LBRACE = 3;
  public static final int ELSE = 23;
  public static final int READ = 17;
  public static final int IF_GREATER_EQUAL = 46;
  public static final int MINUSEQUAL = 32;
  public static final int IF_LESS_EQUAL = 48;
  public static final int IF_NOT_EQUAL = 44;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 40;
  public static final int PROG = 2;
  public static final int MODEQUAL = 35;
  public static final int BOOL_CONST = 21;
  public static final int DEC = 30;
  public static final int MULEQUAL = 33;
  public static final int PRINT = 11;
}

